sample_payload: 'sample_payload.json'
EXPT_DIR : "./log"
DATA_DIR : "./data"
WEIGHTS_DIR : "./weights"
exp_name: "mushroom-experiment-1"

### TRAIN FUNCTION ARGS ###
train_epochs: 10
batch_size: 64
train_size: 6499
learning_rate: 1e-3
momentum: 0.9
split_train: 0.80
